snowflake_dbt_project:
  outputs:
    dev:
      account: RIEDGEY-QHB34599
      database: IVS_ANALYTICS_DWH
      password: Vishjdesai@0506
      role: ACCOUNTADMIN
      schema: raw
      threads: 1
      type: snowflake
      user: VISHAKHADESAI
      warehouse: COMPUTE_WH
  target: dev
